# Generated by Django 5.0 on 2023-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publishing_house', models.CharField(max_length=200, verbose_name='Издательство')),
                ('date', models.DateField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('language', models.CharField(max_length=150, verbose_name='Язык')),
                ('isbn', models.BigIntegerField(verbose_name='ISBN')),
            ],
        ),
    ]
