# Generated by Django 5.0 on 2023-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_genre_language_print_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='date',
            field=models.PositiveIntegerField(verbose_name='Дата основания'),
        ),
    ]
