# Generated by Django 5.0 on 2023-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_print_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
    ]
